package com.elerandir.k8stotfvars;

import com.elerandir.k8stotfvars.model.Comment;
import com.elerandir.k8stotfvars.model.EnvVar;

import java.util.Comparator;
import java.util.List;
import java.util.function.Function;

import lombok.RequiredArgsConstructor;

/**
 * Renders extracted env vars as a Terraform {@code .tfvars} file containing two
 * object maps:
 *
 * <ul>
 *   <li>{@code env_vars} — literal and ConfigMap-resolved variables, with values;</li>
 *   <li>{@code secrets} — Secret-sourced variables, mapped to the Secret key used
 *       to resolve their value elsewhere.</li>
 * </ul>
 *
 * <p>Map keys keep the original variable name verbatim. Comments captured from
 * the source manifest are emitted as Terraform comments next to each entry.
 */
@RequiredArgsConstructor
public final class TfvarsWriter {

    private static final String INDENT = "  ";

    private final boolean header;

    public String render(List<EnvVar> envVars) {
        List<EnvVar> sorted = envVars.stream()
                .sorted(Comparator.comparing(EnvVar::name))
                .toList();

        List<EnvVar> envEntries = sorted.stream()
                .filter(e -> !e.isSecret() && e.resolved())
                .toList();
        List<EnvVar> unresolved = sorted.stream()
                .filter(e -> !e.isSecret() && !e.resolved())
                .toList();
        List<EnvVar> secretEntries = sorted.stream()
                .filter(EnvVar::isSecret)
                .toList();

        StringBuilder sb = new StringBuilder();
        if (header) {
            sb.append("# Generated by k8s-to-tfvars-converter. Do not edit by hand.\n\n");
        }
        appendMap(sb, "env_vars", envEntries, EnvVar::value, unresolved);
        sb.append('\n');
        appendMap(sb, "secrets", secretEntries, EnvVar::secretKey, List.of());
        return sb.toString();
    }

    private void appendMap(StringBuilder sb, String mapName, List<EnvVar> entries,
                           Function<EnvVar, String> valueFn, List<EnvVar> unresolved) {
        if (entries.isEmpty() && unresolved.isEmpty()) {
            sb.append(mapName).append(" = {}\n");
            return;
        }
        int width = entries.stream().mapToInt(e -> keyToken(e.name()).length()).max().orElse(0);

        sb.append(mapName).append(" = {\n");
        for (EnvVar entry : entries) {
            appendComment(sb, entry.comment());
            String key = keyToken(entry.name());
            sb.append(INDENT).append(key).append(" ".repeat(width - key.length()))
                    .append(" = ").append(quote(valueFn.apply(entry)));
            appendInline(sb, entry.comment());
            sb.append('\n');
        }
        for (EnvVar entry : unresolved) {
            // Keep the file valid HCL by emitting unresolved vars as comments.
            sb.append(INDENT).append("# ").append(keyToken(entry.name()))
                    .append(" = null  # unresolved: ").append(entry.origin()).append('\n');
        }
        sb.append("}\n");
    }

    private static void appendComment(StringBuilder sb, Comment comment) {
        for (String line : comment.lines()) {
            sb.append(INDENT).append("# ").append(line).append('\n');
        }
    }

    private static void appendInline(StringBuilder sb, Comment comment) {
        if (comment.inline() != null) {
            sb.append(" # ").append(comment.inline());
        }
    }

    /** A map key, always rendered as a quoted string. */
    static String keyToken(String name) {
        return quote(name);
    }

    /** Quote and escape a value as an HCL string literal. */
    static String quote(String value) {
        String safe = value == null ? "" : value;
        // Escape Terraform template sequences first so literal "${...}"/"%{...}"
        // in values are not interpreted as interpolations.
        String escaped = safe.replace("${", "$${").replace("%{", "%%{");
        StringBuilder sb = new StringBuilder(escaped.length() + 2);
        sb.append('"');
        for (int i = 0; i < escaped.length(); i++) {
            char c = escaped.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }
        sb.append('"');
        return sb.toString();
    }
}
