package com.elerandir.k8stotfvars;

import com.elerandir.k8stotfvars.model.EnvVar;

import java.util.Comparator;
import java.util.List;

/**
 * Renders a list of {@link EnvVar} as the contents of a Terraform {@code .tfvars}
 * file: one {@code key = "value"} assignment per line, keys sorted for stable
 * output.
 */
public final class TfvarsWriter {

    private final boolean header;

    public TfvarsWriter(boolean header) {
        this.header = header;
    }

    public String render(List<EnvVar> envVars) {
        StringBuilder sb = new StringBuilder();
        if (header) {
            sb.append("# Generated by k8s-to-tfvars-converter. Do not edit by hand.\n");
            sb.append("# Each variable corresponds to a container environment variable.\n\n");
        }
        envVars.stream()
                .sorted(Comparator.comparing(EnvVar::name))
                .forEach(envVar -> appendAssignment(sb, envVar));
        return sb.toString();
    }

    private static void appendAssignment(StringBuilder sb, EnvVar envVar) {
        if (envVar.value() == null) {
            // Unresolved value: emit a commented placeholder so the file stays valid HCL.
            sb.append("# ").append(sanitizeKey(envVar.name()))
                    .append(" = null  # unresolved: ").append(envVar.origin()).append('\n');
            return;
        }
        sb.append(sanitizeKey(envVar.name()))
                .append(" = ")
                .append(quote(envVar.value()))
                .append('\n');
    }

    /**
     * Terraform variable names must start with a letter or underscore and contain
     * only letters, digits, underscores, and hyphens. Any other character is
     * replaced with an underscore.
     */
    static String sanitizeKey(String name) {
        StringBuilder sb = new StringBuilder(name.length() + 1);
        // A leading digit is invalid; prefix an underscore rather than dropping it.
        if (!name.isEmpty() && name.charAt(0) >= '0' && name.charAt(0) <= '9') {
            sb.append('_');
        }
        for (int i = 0; i < name.length(); i++) {
            char c = name.charAt(i);
            boolean ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
                    || (c >= '0' && c <= '9')
                    || (c == '_') || (c == '-');
            sb.append(ok ? c : '_');
        }
        return sb.toString();
    }

    /** Quote and escape a value as an HCL string literal. */
    static String quote(String value) {
        // Escape Terraform template sequences first so literal "${...}"/"%{...}"
        // in env values are not interpreted as interpolations.
        String escaped = value.replace("${", "$${").replace("%{", "%%{");
        StringBuilder sb = new StringBuilder(escaped.length() + 2);
        sb.append('"');
        for (int i = 0; i < escaped.length(); i++) {
            char c = escaped.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }
        sb.append('"');
        return sb.toString();
    }
}
